## This is a script to generate an example .sqw4 file and make a plot. 
## The test case will be a simple acoustic and optical phonon / spin-wave excitation. 

import numpy as np 
import matplotlib.pyplot as plt 

# The format will match files generated by iFit. 

# Files generated by iFit have the following header : 
# lattice_a 4.135
# lattice_b 4.135
# lattice_c 4.135
# lattice_aa 90
# lattice_bb 90
# lattice_cc 90
# temperature 2
# field||a 0
# field||b 0
# field||c 0
# column_h 1
# column_k 2
# column_l 3
# column_E 4
# column_S 5
# h k l En S(q,w)

# In our case we use an example that is known to have a well-behaved
# LSWT excitation spectra, for comparison to SpinW, Elemental Gd

